### ISSUE TITLE
Maintain ( cordova 10 / deprecated dependencies  )

### ISSUE THREAD

**Issue by CrackerakiUA** [KevinWang15/cordova-app-updater#4]
Two of the dependencies was deprecated, `cordova-plugin-file-transfer` and `crypto`. Do you plan to update use of the plagin?
Trying out the demo with Cordova 10 and can't manage to make it work. There is no package.json file which should tell what we need to use.
In demo it's not your repo which we clone, is that as it should be?

**Comment by KevinWang15** [comment]
Sorry, this project was created in 2016 and is no longer maintained
You can try alternatives such as Microsoft code push
https://github.com/microsoft/cordova-plugin-code-push
https://github.com/lisong/code-push-server
